Add more output to help command
bolcom/libunftp pull request #471
Opened 2023-07-09 18:26 UTC by joostderuijter

Closes #40. Issuing an help command now also returns a link to the docs (https://unftp.rs/) & the libunftp version.

2023-07-09 20:02 UTC, hannesdejager commented
Very nice, thank you!!

2023-07-09 20:04 UTC, hannesdejager approved these changes
LGTM

2023-07-09 20:05 UTC, hannesdejager requested changes
OK, format check fails.

Please run `cargo fmt` and push again.

Also run `make pr-prep` to ensure all is good.

2023-07-09 20:21 UTC, joostderuijter commented
Thanks, I'll keep it in mind for the future. I'll update the PR

2023-07-12 11:19 UTC, robklg approved these changes

2023-08-13 12:42 UTC, merged